Autenticacao
EduardoScarante/vitrine-4net pull request #2
Opened 2023-07-11 13:36 UTC by Wes7ey

Essa PR cria a view de Access que tem os componentes para cadastro e login
Estiliza os componentes, o background do layout

2023-07-11 14:52 UTC, EduardoScarante approved these changes

2023-07-11 16:22 UTC, abimaelneto commented on src/modules/auth/components/Login.vue
> +  console.log("deu certo")
remover log
```suggestion
```

2023-07-11 16:23 UTC, abimaelneto commented on src/modules/auth/components/Register.vue
> +<script setup>
alguns arquivos estão com script em cima do template, outros embaixo. Seria legal escolher um padrão

2023-07-11 16:27 UTC, abimaelneto commented on src/modules/auth/view/Access.vue
> +            Não tem cadastro
```suggestion
            Não tenho cadastro
```

2023-07-11 16:29 UTC, abimaelneto requested changes
sugeri alguns detalhes, se puder dar uma olhada ;)

2023-07-11 17:45 UTC, Wes7ey commented
> sugeri alguns detalhes, se puder dar uma olhada ;)

Correções realizadas, também já inclui o redirecionamento da tela de Login para a Home

2023-07-12 12:19 UTC, abimaelneto approved these changes
@Wes7ey mano, me senti lisonjeado, mas por padrão não precisa citar meu nome nos commits kkkkk

2023-07-12 12:35 UTC, merged